import Head from "next/head";

const posts = [
  {
    name: "MERN Stack Praktikum",
    excerpt: "MongoDB, ExpressJs, ReactJs, NodeJs",
  },
  {
    name: "Digital Marketing",
    excerpt: "ADS, Instagram, Telegram",
  },
];

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
            <div>
              {post.name}
              {post.excerpt}
            </div>
          ))}
        </div>
      </div>
      <div className="lg:col-span-8 col-span-1">
        <div className="lg:sticky relative top-8"></div>
      </div>
    </div>
  );
}
